
@url = http://localhost:4400

GET {{url}}/photosapi

###

GET {{url}}/photosapi/1

###
GET {{url}}/employeesapi

###
GET {{url}}/employeessp

###
GET {{url}}/employeesapi/3

###
POST {{url}}/login
Content-Type: application/json

{
    "email": "john@vanarts.com",
    "password": "654321"
}

###
POST {{url}}/signup 
Content-Type: application/json

{
    "email": "asdfasf",
    "password": "123"
}

###
PUT {{url}}/updateUser
Content-Type: application/json

{
    "UserID": 3,
    "email": "b@b.com",
    "password": "321"
}

###
DELETE {{url}}/deleteuser/12

###
GET {{url}}/user/5