
@url = http://localhost:4400

GET {{url}}/photosapi

###

GET {{url}}/photosapi/1

###
GET {{url}}/employeesapi

###
GET {{url}}/employeessp

###
GET {{url}}/employeesapi/3

###
POST {{url}}/login
Content-Type: application/json

{
    "email": "john@vanarts.com0",
    "password": "654321"
}

###
POST {{url}}/signup 
Content-Type: application/json

{
    "name": "Bob Smith",
    "email": "asdfasf",
    "city": "Surrey"
}